/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Bootloadable.h>
#include <Clock_3.h>
#include <Green.h>
#include <Green_aliases.h>
#include <PWM_GreenYellow.h>
#include <White.h>
#include <White_aliases.h>
#include <PWM_Red.h>
#include <Clock_1.h>
#include <PWM_BlueWhite.h>
#include <Clock_2.h>
#include <Yellow.h>
#include <Yellow_aliases.h>
#include <Blue.h>
#include <Blue_aliases.h>
#include <Red.h>
#include <Red_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

